import { PDFTool, ToolCategory } from '@/types/tools';

export const CATEGORIES: Array<{ id: ToolCategory; name: string; description: string }> = [
  { id: 'workflow', name: 'Workflow', description: 'Automate multiple PDF operations sequentially' },
  { id: 'organize', name: 'Organize', description: 'Merge, split, reorder, rotate and structure PDF documents' },
  { id: 'edit', name: 'Edit & Annotate', description: 'Add signatures, forms, redactions, watermarks and numbering' },
  { id: 'handwriting', name: 'Handwriting', description: 'Simulate and convert realistic handwritten documents' },
  { id: 'create', name: 'Create PDF', description: 'Generate PDFs from documents, images, code and spreadsheets' },
  { id: 'convert', name: 'Convert From PDF', description: 'Export PDFs into Word, Excel, PowerPoint, Images and audio' },
  { id: 'security', name: 'Security & Metadata', description: 'Protect, decrypt, compress and update document information' },
];

export const PDF_TOOLS: PDFTool[] = [
  // Workflow
  {
    id: 'workflow',
    name: 'PDF Workflow Builder',
    shortName: 'Workflow Builder',
    description: 'Chain multiple PDF operations into an automated custom pipeline',
    category: 'workflow',
    icon: 'Workflow',
    badge: 'Automation',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },

  // Organize
  {
    id: 'merge',
    name: 'Merge PDFs',
    shortName: 'Merge',
    description: 'Combine multiple PDF files into a single unified document in any order',
    category: 'organize',
    icon: 'Combine',
    badge: 'Popular',
    acceptsMultipleFiles: true,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'alternate-mix',
    name: 'Alternate & Mix PDF',
    shortName: 'Alternate & Mix',
    description: 'Interleave pages from two or more PDFs alternating page-by-page or custom pattern',
    category: 'organize',
    icon: 'Shuffle',
    acceptsMultipleFiles: true,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'split',
    name: 'Split PDF',
    shortName: 'Split',
    description: 'Divide a PDF into separate files by page ranges or extract individual pages',
    category: 'organize',
    icon: 'Scissors',
    badge: 'Popular',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'split-text',
    name: 'Split PDF by Text',
    shortName: 'Split by Text',
    description: 'Split document whenever specific text patterns or keywords appear on a page',
    category: 'organize',
    icon: 'FileSearch',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'split-bookmarks',
    name: 'Split PDF by Bookmarks',
    shortName: 'Split by Bookmarks',
    description: 'Detect PDF outline and split document into chapters based on bookmark levels',
    category: 'organize',
    icon: 'Bookmark',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'split-half',
    name: 'Split PDF in Half',
    shortName: 'Split in Half',
    description: 'Split dual-page scans vertically or horizontally into two separate pages',
    category: 'organize',
    icon: 'Columns',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'split-size',
    name: 'Split PDF by Size',
    shortName: 'Split by Size',
    description: 'Automatically segment a large PDF into parts under a specified maximum file size',
    category: 'organize',
    icon: 'HardDrive',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'organize',
    name: 'Organize Pages',
    shortName: 'Organize',
    description: 'Visual grid editor to reorder, delete, duplicate, select, and rotate PDF pages',
    category: 'organize',
    icon: 'LayoutGrid',
    badge: 'Interactive',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    shortName: 'Rotate',
    description: 'Rotate all or specific pages by 90°, 180°, or 270° clockwise or counter-clockwise',
    category: 'organize',
    icon: 'RotateCw',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'flip',
    name: 'Flip PDF',
    shortName: 'Flip',
    description: 'Mirror PDF pages horizontally or vertically across the entire document or selections',
    category: 'organize',
    icon: 'FlipHorizontal',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'n-up',
    name: 'Multiple Pages Per Sheet',
    shortName: 'N-Up Pages',
    description: 'Place 2, 4, 6, or 8 pages per sheet with custom margins, borders, and orientation',
    category: 'organize',
    icon: 'Grid',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'crop-resize',
    name: 'Crop & Resize',
    shortName: 'Crop & Resize',
    description: 'Visually crop margins or resize PDF page dimensions to A4, Letter, A3, or custom',
    category: 'organize',
    icon: 'Crop',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    shortName: 'Compress',
    description: 'Reduce PDF file size with Low, Medium, or High compression while preserving quality',
    category: 'organize',
    icon: 'Minimize2',
    badge: 'Popular',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },

  // Edit & Annotate
  {
    id: 'edit',
    name: 'Edit PDF & Add Signature',
    shortName: 'Edit PDF',
    description: 'Interactive canvas to add text, signatures, images, highlights, dates, and shapes',
    category: 'edit',
    icon: 'PenTool',
    badge: 'Editor',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    shortName: 'Sign',
    description: 'Draw, type, or upload your signature and stamp it accurately onto any page',
    category: 'edit',
    icon: 'FileSignature',
    badge: 'Essential',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'fill-form',
    name: 'Fill PDF Form',
    shortName: 'Fill Form',
    description: 'Detect, inspect, and fill interactive PDF text fields, checkboxes, and radio buttons',
    category: 'edit',
    icon: 'CheckSquare',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'redact',
    name: 'Redact PDF',
    shortName: 'Redact',
    description: 'Permanently remove and sanitize sensitive confidential text and areas from PDF',
    category: 'edit',
    icon: 'EyeOff',
    badge: 'Security',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'watermark',
    name: 'Add Watermark',
    shortName: 'Watermark',
    description: 'Apply customizable text or transparent image watermarks with angle and opacity',
    category: 'edit',
    icon: 'Stamp',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'page-numbers',
    name: 'Add Page Numbers',
    shortName: 'Page Numbers',
    description: 'Number your pages with custom positioning, starting index, and layout formats',
    category: 'edit',
    icon: 'Binary',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'bates',
    name: 'Bates Numbering',
    shortName: 'Bates Stamp',
    description: 'Legal document indexing with customized prefix, digit padding, and increments',
    category: 'edit',
    icon: 'ListOrdered',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'header-footer',
    name: 'Headers & Footers',
    shortName: 'Headers/Footers',
    description: 'Add dynamic header and footer text with page numbers, date, filename, and margins',
    category: 'edit',
    icon: 'AlignJustify',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'flatten',
    name: 'Flatten PDF',
    shortName: 'Flatten',
    description: 'Bake annotations, drawing layers, and form fields directly into non-editable page content',
    category: 'edit',
    icon: 'FileCheck',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'invert',
    name: 'Invert PDF Colours',
    shortName: 'Invert Colours',
    description: 'Convert document into high-contrast dark mode or invert colors for easy reading',
    category: 'edit',
    icon: 'Moon',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'thumbmark',
    name: 'Thumbmark Maker',
    shortName: 'Thumbmark',
    description: 'Generate realistic digital biometric thumbprints / fingerprints and position on pages',
    category: 'edit',
    icon: 'Fingerprint',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },

  // Handwriting
  {
    id: 'pdf-to-handwriting',
    name: 'PDF to Handwriting',
    shortName: 'PDF to Handwriting',
    description: 'Transform regular typed PDF pages into handwritten script with customizable ink',
    category: 'handwriting',
    icon: 'Feather',
    badge: 'Creative',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'text-to-handwriting',
    name: 'Text to Handwriting',
    shortName: 'Text to Handwriting',
    description: 'Convert typed text into realistic handwritten notebook pages or assignments',
    category: 'handwriting',
    icon: 'Pen',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.txt'],
  },
  {
    id: 'handwriting-to-pdf',
    name: 'Handwriting to PDF',
    shortName: 'Handwriting to PDF',
    description: 'Convert handwritten photos, scans, and notebook snapshots into polished clean PDF',
    category: 'handwriting',
    icon: 'ImagePlus',
    acceptsMultipleFiles: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
  },

  // Create PDF
  {
    id: 'create-pdf',
    name: 'Create PDF',
    shortName: 'Create Blank',
    description: 'Create a new custom PDF document from scratch with text, images, and layout',
    category: 'create',
    icon: 'PlusCircle',
    acceptsMultipleFiles: false,
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    shortName: 'Images to PDF',
    description: 'Convert JPG, PNG, WEBP and GIF images into a clean multi-page PDF',
    category: 'create',
    icon: 'Images',
    badge: 'Popular',
    acceptsMultipleFiles: true,
    acceptedFileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    shortName: 'Word to PDF',
    description: 'Convert DOC and DOCX Word documents into standard PDF pages',
    category: 'create',
    icon: 'FileText',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.docx', '.doc'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    shortName: 'Excel to PDF',
    description: 'Render XLS and XLSX spreadsheet sheets and tables into formatted PDF pages',
    category: 'create',
    icon: 'Table',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.xlsx', '.xls'],
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    shortName: 'PPT to PDF',
    description: 'Convert presentation slides into high-resolution PDF document',
    category: 'create',
    icon: 'Presentation',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pptx', '.ppt'],
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    shortName: 'HTML to PDF',
    description: 'Convert HTML code snippets, web pages, or HTML files directly into PDF',
    category: 'create',
    icon: 'Code',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.html', '.htm'],
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    shortName: 'Markdown to PDF',
    description: 'Live Markdown editor with instant styling preview and high-quality PDF export',
    category: 'create',
    icon: 'FileCode',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.md', '.txt'],
  },
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    shortName: 'Resume to PDF',
    description: 'Modern CV & resume builder with customizable templates and instant PDF generation',
    category: 'create',
    icon: 'Briefcase',
    badge: 'New',
    acceptsMultipleFiles: false,
  },
  {
    id: 'csv-to-pdf',
    name: 'CSV to PDF',
    shortName: 'CSV to PDF',
    description: 'Format tabular CSV data into clean, styled, ready-to-print PDF tables',
    category: 'create',
    icon: 'FileSpreadsheet',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.csv'],
  },
  {
    id: 'audio-to-pdf',
    name: 'Audio to PDF',
    shortName: 'Audio to PDF',
    description: 'Record voice or load speech audio transcript and format into a PDF document',
    category: 'create',
    icon: 'Mic',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.mp3', '.wav', '.ogg', '.m4a'],
  },
  {
    id: 'ebook-to-pdf',
    name: 'eBook to PDF',
    shortName: 'eBook to PDF',
    description: 'Convert digital book text and EPUB formats into a readable formatted PDF',
    category: 'create',
    icon: 'BookOpen',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.epub', '.txt'],
  },

  // Convert From PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    shortName: 'PDF to DOCX',
    description: 'Extract layout and text paragraphs into editable Microsoft Word (.docx) document',
    category: 'convert',
    icon: 'FileType',
    badge: 'Popular',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    shortName: 'PDF to JPG',
    description: 'Render every PDF page into high-definition JPG images, individual or as a ZIP',
    category: 'convert',
    icon: 'Image',
    badge: 'Popular',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    shortName: 'PDF to XLSX',
    description: 'Detect tabular structures in PDF and export directly to Microsoft Excel spreadsheet',
    category: 'convert',
    icon: 'Sheet',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    shortName: 'PDF to PPTX',
    description: 'Convert PDF pages into PowerPoint presentation slides (.pptx)',
    category: 'convert',
    icon: 'Tv',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    shortName: 'PDF to HTML',
    description: 'Convert PDF content and pages into clean, responsive HTML web pages',
    category: 'convert',
    icon: 'Globe',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-audio',
    name: 'PDF to Audio',
    shortName: 'PDF to Audio',
    description: 'Listen to your PDF document or export spoken audio using natural browser TTS',
    category: 'convert',
    icon: 'Volume2',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-epub',
    name: 'PDF to EPUB',
    shortName: 'PDF to EPUB',
    description: 'Convert PDF text and chapters into standard EPUB ebook format for e-readers',
    category: 'convert',
    icon: 'Book',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'extract-text',
    name: 'Extract Text',
    shortName: 'Extract Text',
    description: 'Pull all plain or formatted text from PDF pages with one click or export to TXT',
    category: 'convert',
    icon: 'FileOutput',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'extract-images',
    name: 'Extract Images from PDF',
    shortName: 'Extract Images',
    description: 'Detect and extract all embedded photos, diagrams, and illustrations inside the PDF',
    category: 'convert',
    icon: 'Camera',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'pdf-to-zip',
    name: 'PDF to ZIP',
    shortName: 'PDF to ZIP',
    description: 'Package PDF pages, separated documents, or extracted assets into a single ZIP archive',
    category: 'convert',
    icon: 'Archive',
    acceptsMultipleFiles: true,
    acceptedFileTypes: ['.pdf'],
  },

  // Security
  {
    id: 'encrypt',
    name: 'Encrypt PDF',
    shortName: 'Protect PDF',
    description: 'Protect confidential PDF with strong user password and owner permissions',
    category: 'security',
    icon: 'Lock',
    badge: 'Privacy',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'remove-password',
    name: 'Remove Password',
    shortName: 'Remove Password',
    description: 'Provide master password to unlock and create an unrestricted copy of the PDF',
    category: 'security',
    icon: 'KeyRound',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    shortName: 'Unlock PDF',
    description: 'Enter document password to decrypt and preview protected PDF in browser',
    category: 'security',
    icon: 'Unlock',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
  {
    id: 'metadata',
    name: 'Edit PDF Metadata',
    shortName: 'Edit Metadata',
    description: 'View and update Title, Author, Subject, Keywords, Creator, and Producer info',
    category: 'security',
    icon: 'Info',
    acceptsMultipleFiles: false,
    acceptedFileTypes: ['.pdf'],
  },
];

export function getToolById(id: string): PDFTool | undefined {
  return PDF_TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: ToolCategory): PDFTool[] {
  return PDF_TOOLS.filter((tool) => tool.category === category);
}

export function searchTools(query: string): PDFTool[] {
  const q = query.trim().toLowerCase();
  if (!q) return PDF_TOOLS;
  return PDF_TOOLS.filter(
    (tool) =>
      tool.name.toLowerCase().includes(q) ||
      tool.description.toLowerCase().includes(q) ||
      (tool.shortName && tool.shortName.toLowerCase().includes(q)) ||
      tool.category.toLowerCase().includes(q)
  );
}
